// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: main.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_main_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{0}
}

type FetchMultiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	N             uint32                 `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMultiRequest) Reset() {
	*x = FetchMultiRequest{}
	mi := &file_main_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMultiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMultiRequest) ProtoMessage() {}

func (x *FetchMultiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMultiRequest.ProtoReflect.Descriptor instead.
func (*FetchMultiRequest) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{1}
}

func (x *FetchMultiRequest) GetN() uint32 {
	if x != nil {
		return x.N
	}
	return 0
}

type FetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_main_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{2}
}

func (x *FetchResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FetchMultiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint64               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMultiResponse) Reset() {
	*x = FetchMultiResponse{}
	mi := &file_main_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMultiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMultiResponse) ProtoMessage() {}

func (x *FetchMultiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMultiResponse.ProtoReflect.Descriptor instead.
func (*FetchMultiResponse) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{3}
}

func (x *FetchMultiResponse) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_main_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{4}
}

type StatsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Pid              int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Uptime           int64                  `protobuf:"varint,2,opt,name=uptime,proto3" json:"uptime,omitempty"`
	Time             int64                  `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	Version          string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	CurrConnections  int64                  `protobuf:"varint,5,opt,name=curr_connections,json=currConnections,proto3" json:"curr_connections,omitempty"`
	TotalConnections int64                  `protobuf:"varint,6,opt,name=total_connections,json=totalConnections,proto3" json:"total_connections,omitempty"`
	CmdGet           int64                  `protobuf:"varint,7,opt,name=cmd_get,json=cmdGet,proto3" json:"cmd_get,omitempty"`
	GetHits          int64                  `protobuf:"varint,8,opt,name=get_hits,json=getHits,proto3" json:"get_hits,omitempty"`
	GetMisses        int64                  `protobuf:"varint,9,opt,name=get_misses,json=getMisses,proto3" json:"get_misses,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_main_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_main_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_main_proto_rawDescGZIP(), []int{5}
}

func (x *StatsResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *StatsResponse) GetUptime() int64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *StatsResponse) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *StatsResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StatsResponse) GetCurrConnections() int64 {
	if x != nil {
		return x.CurrConnections
	}
	return 0
}

func (x *StatsResponse) GetTotalConnections() int64 {
	if x != nil {
		return x.TotalConnections
	}
	return 0
}

func (x *StatsResponse) GetCmdGet() int64 {
	if x != nil {
		return x.CmdGet
	}
	return 0
}

func (x *StatsResponse) GetGetHits() int64 {
	if x != nil {
		return x.GetHits
	}
	return 0
}

func (x *StatsResponse) GetGetMisses() int64 {
	if x != nil {
		return x.GetMisses
	}
	return 0
}

var File_main_proto protoreflect.FileDescriptor

const file_main_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"main.proto\x12\n" +
	"katsubushi\"\x0e\n" +
	"\fFetchRequest\"!\n" +
	"\x11FetchMultiRequest\x12\f\n" +
	"\x01n\x18\x01 \x01(\rR\x01n\"\x1f\n" +
	"\rFetchResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"&\n" +
	"\x12FetchMultiResponse\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x04R\x03ids\"\x0e\n" +
	"\fStatsRequest\"\x92\x02\n" +
	"\rStatsResponse\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x16\n" +
	"\x06uptime\x18\x02 \x01(\x03R\x06uptime\x12\x12\n" +
	"\x04time\x18\x03 \x01(\x03R\x04time\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12)\n" +
	"\x10curr_connections\x18\x05 \x01(\x03R\x0fcurrConnections\x12+\n" +
	"\x11total_connections\x18\x06 \x01(\x03R\x10totalConnections\x12\x17\n" +
	"\acmd_get\x18\a \x01(\x03R\x06cmdGet\x12\x19\n" +
	"\bget_hits\x18\b \x01(\x03R\agetHits\x12\x1d\n" +
	"\n" +
	"get_misses\x18\t \x01(\x03R\tgetMisses2\x9a\x01\n" +
	"\tGenerator\x12>\n" +
	"\x05Fetch\x12\x18.katsubushi.FetchRequest\x1a\x19.katsubushi.FetchResponse\"\x00\x12M\n" +
	"\n" +
	"FetchMulti\x12\x1d.katsubushi.FetchMultiRequest\x1a\x1e.katsubushi.FetchMultiResponse\"\x002E\n" +
	"\x05Stats\x12<\n" +
	"\x03Get\x12\x18.katsubushi.StatsRequest\x1a\x19.katsubushi.StatsResponse\"\x00Bt\n" +
	"\x0ecom.katsubushiB\tMainProtoP\x01Z\x0fkatsubushi/grpc\xa2\x02\x03KXX\xaa\x02\n" +
	"Katsubushi\xca\x02\n" +
	"Katsubushi\xe2\x02\x16Katsubushi\\GPBMetadata\xea\x02\n" +
	"Katsubushib\x06proto3"

var (
	file_main_proto_rawDescOnce sync.Once
	file_main_proto_rawDescData []byte
)

func file_main_proto_rawDescGZIP() []byte {
	file_main_proto_rawDescOnce.Do(func() {
		file_main_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_main_proto_rawDesc), len(file_main_proto_rawDesc)))
	})
	return file_main_proto_rawDescData
}

var file_main_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_main_proto_goTypes = []any{
	(*FetchRequest)(nil),       // 0: katsubushi.FetchRequest
	(*FetchMultiRequest)(nil),  // 1: katsubushi.FetchMultiRequest
	(*FetchResponse)(nil),      // 2: katsubushi.FetchResponse
	(*FetchMultiResponse)(nil), // 3: katsubushi.FetchMultiResponse
	(*StatsRequest)(nil),       // 4: katsubushi.StatsRequest
	(*StatsResponse)(nil),      // 5: katsubushi.StatsResponse
}
var file_main_proto_depIdxs = []int32{
	0, // 0: katsubushi.Generator.Fetch:input_type -> katsubushi.FetchRequest
	1, // 1: katsubushi.Generator.FetchMulti:input_type -> katsubushi.FetchMultiRequest
	4, // 2: katsubushi.Stats.Get:input_type -> katsubushi.StatsRequest
	2, // 3: katsubushi.Generator.Fetch:output_type -> katsubushi.FetchResponse
	3, // 4: katsubushi.Generator.FetchMulti:output_type -> katsubushi.FetchMultiResponse
	5, // 5: katsubushi.Stats.Get:output_type -> katsubushi.StatsResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_main_proto_init() }
func file_main_proto_init() {
	if File_main_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_main_proto_rawDesc), len(file_main_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_main_proto_goTypes,
		DependencyIndexes: file_main_proto_depIdxs,
		MessageInfos:      file_main_proto_msgTypes,
	}.Build()
	File_main_proto = out.File
	file_main_proto_goTypes = nil
	file_main_proto_depIdxs = nil
}
